[package]
name = "rust_pdf_cleaner"
version = "0.1.0"
authors = ["Julien Wetzel <julienwetzel@gmail.com>"]
edition = "2021"

[dependencies]
image = "0.24.6"
mupdf = "0.4.2"
#lopdf = { version = "0.29.0", default-features = false, features = ["pom_parser", "nom_parser"]}